### ISSUE TITLE
[Help] Decoding with sigrok

### ISSUE THREAD

**Issue by uploader18** [issalig/toshiba_air_cond#10] opened 2022-01-01 19:52 UTC
I am working in decoding Toshiba indoor to outdoor communication protocol and need help.I have a wave form taken with sigrok and can't decode it.

If you are so kind write me an email so i have yours.

My mail: uploader18@gmail.com

Regards Ziga

**Comment by issalig** [comment] 2022-01-01 20:14
Hi, for technical stuff I prefer to communicate through github, that way others can learn and contribute.

Some things you should take into account when using sigrok and saelae logic analizer
- sampling rate, according to Nyquist theorem it should be at least 2x than the frequency you want to capture.
- be sure signal is in the range 0 - 3.3V (not sure if it is 5V, so I stay safe at 3.3v)

Not sure if you still tried but in order to decode (serial protocol) , you should go for the decoder (waveform icon in pulseview) and select UART. And then try all the different combinations :)

Can you share the waveform? wetransfer, pastebin, etc, ...

BR

**Comment by uploader18** [comment] 2022-01-01 20:50
Hi, I agree with you that we should share it over github but till now i
only know it is ModBusRTU protocol, 300 baudrate and that is it.I am
attaching sigrok file and page from service manual on what data is sent to
outdoor unit.For now i only have data from cooling mode.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

V V sob., 1. jan. 2022 ob 21:14 je oseba issalig ***@***.***>
napisala:

**Comment by uploader18** [comment] 2022-01-01 21:00
Hi, I agree with you that we should share it over github but till now i only know it is ModBusRTU protocol, 300 baudrate and that is it.I am attaching sigrok file and page from service manual on what data is sent to outdoor unit.For now i only have data from cooling mode.

[cooling 17c vent3.zip](https://github.com/issalig/toshiba_air_cond/files/7798231/cooling.17c.vent3.zip)
![4738f2f73e8f015cd7c7a6a0ae4a5326b025caea_2_225x500](https://user-images.githubusercontent.com/42915702/147860102-5d1c32ba-07e5-413f-bde8-7b63a0dd86f8.jpeg)
![2e74b51e63d1659cdc689ab5cbbe0ad0fba81541_2_225x500](https://user-images.githubusercontent.com/42915702/147860104-f542a55f-2f7e-45a9-8236-756c898d61c7.jpeg)

**Comment by issalig** [comment] 2022-01-01 22:41
Looks like .sal format is not supported by sigrok (at least my installation, maybe recompiling with saleae format support could be possible, but haven't tried)

Can you provide a CSV file or other format?

**Comment by uploader18** [comment] 2022-01-01 22:44
I used Logic 2 to capture it.

https://support.saleae.com/logic-software/sw-download

Regards, Ziga

**Comment by issalig** [comment] 2022-01-01 23:31
Ok, I loaded it into Logic2 and what I see looks that there are problems with signal, small pulses that can be noise, a poor voltage level, maybe less than 2V (see https://en.wikipedia.org/wiki/Logic_level) 

I also see that in RX this small pulses are 167 ns wide that would be 6Mhz approx 6000000 baudrate that it is not what is expected, I guess it will be more in the range of 2400 (typical values are 110, 300, 600, 1200, 2400, 4800, 9600, 14400, 19200, 38400, 57600, 115200, 128000 and 256000 )

Try to set this filter  https://support.saleae.com/user-guide/using-logic/software-glitch-filter and capture the signal again.

If you have and oscilloscope try to visualize the signal, the smallest pulse (given there are no glitches) will tell you the baudrate


![image](https://user-images.githubusercontent.com/7136948/147862123-71940fce-8de7-44c2-a1b0-e2bd74f0f420.png)

**Comment by issalig** [comment] 2022-01-02 11:01
I played this morning a little bit, for RX signal the shortest pulse shows that it could be a 100 bps signal (also a 150bps), then playing with standard 8N1 produces a result without framing errors that does not mean it is the right one but a candidate. 
But it is strange that "0" pulses are about 7.5 ms while "1" are 11.93 ms, 
I guessed the baudrate manually but here they give some hints and there is even an extension https://support.saleae.com/protocol-analyzers/analyzer-user-guides/using-async-serial

For TX there are a lot of errors, probably caused by the glitches that confuse the decoder.
It is also worth to notice that there are 1.66 ms "0" pulses that do not seem to be just noise, but this pulse width would mean much higher baudrate while RX line seems to be around 100.

![Captura de pantalla de 2022-01-02 11-44-22](https://user-images.githubusercontent.com/7136948/147873332-e8129ebe-b8b2-49c1-bad5-bdf84b381586.png)

I attach you the .sal file with the decoding
[cooling_17c_vent3_serial.zip](https://github.com/issalig/toshiba_air_cond/files/7798945/cooling_17c_vent3_serial.zip)

**Comment by uploader18** [comment] 2022-01-02 16:26
I captured it again with 1us filter

[cooling mode with 1us filter.zip](https://github.com/issalig/toshiba_air_cond/files/7799419/cooling.mode.with.1us.filter.zip)

**Comment by issalig** [comment] 2022-01-02 18:24
It looks better glitches are over, but this small pulses in the TX line confuse me (see image). Also RX line look like a CLK signal

How do you get pulsview output? Just using pulseview or converting it from .sal ?

I have been able to decode without errors using serial protocol with 120 baudrate 8N1  and RX non-inverted and TX inverted but I do not think thos e are the right parameters, they just fit. 
![image](https://user-images.githubusercontent.com/7136948/147885533-d3ce2790-8648-4b5c-8061-8215b36732ea.png)

Do you have experience with modbus? Do you think is it a modbus signal?

**Comment by uploader18** [comment] 2022-01-02 18:54
There is no RX or TX line it is single wire and ground it communicates over power cables. I am adding a picture from service manual so you can see how it is connected.

I used pulsewiev.

With serial protocol it is too easy or is it, if it is then we must check, i will make a signal capture with cooling and one with heating and we will see what if anything changes and to be sure I will capture first for cooling twice in a row and heating twice so that we see if anything changes.

![SM-comm](https://user-images.githubusercontent.com/42915702/147886359-683f4ac8-bbda-4d26-89a1-eb36b8f37517.JPG)

**Comment by issalig** [comment] 2022-01-02 20:25
So, which cables are you analising, blk, whi, red from the indoor/outdoor unit.
Do you have an oscilloscope to check the real signal?

**Comment by uploader18** [comment] 2022-01-02 21:32
No, i am measuring directly on MCU RX and TX line
![Indoor_pcb_LI](https://user-images.githubusercontent.com/42915702/147889986-69b930ac-8e05-45ef-a429-840fd9c8dcf2.jpg)
s

**Comment by uploader18** [comment] 2022-01-04 21:21
hey, i was thinking what if it is a SPI serial communication since by pulse waves it looks like full duplex communication and is uses 50hz as clock from power source, that would explain why pulses are 20ms wide.......??

**Comment by issalig** [comment] 2022-01-04 22:07
Hmm, but it there are olny 2 lines , then it would be i2c (SCL , SDA), does not it?
But the thing is that SPI and i2c are used to interconnect elements in a board, not to send it outdoor/large distances. Maybe you are just reading an element from the board (sensor maybe) that communicates with the main board.

Anyway, we are learning a lot. :)

**Comment by uploader18** [comment] 2022-01-04 22:37
When looking at PCB, transmiter and reciver are connected via optocouplers together and then data is sent over one wire. Clock is taken from 50hz mains on both sides indoor and outdoor unit so there is no need for clock wire.

**Comment by issalig** [comment] 2022-01-05 08:50
I wanted to say that SPI requires 4 lines SCLK, MISO, MOSI and SS so i2c makes more sense. However this 50hz signal is strange, normally it is just noise from the mains but data fits this clock signal.
Also from the decoding i2c has no sense to me because there are only addresses and not data. Typical i2c communication would be address+data, address+data, ...

**Comment by uploader18** [comment] 2022-01-05 14:18
I think that it is not pure spi but modified spi communication since MCU uses rx and tx lines and mains 50hz for clock.there is no need for SS pin since there is only master and one slave. For now i know that data sent from indoor unit(master) to outdoor(slave) is 

Indoor umit capacity
Cooling or heating
Capacity demand
Indoor heat exchanger temperature

I think we are close.

**Comment by issalig** [comment] 2022-01-05 16:40
My code can access to heat exchanger temperatures but also it can be done through the wired controller, pg 18 from http://www.toshiba-aircon.co.uk/assets/uploads/product_assets/20131115_IM_1115460101_Standard_Duct_RAV-SM_6BTP-E_EN.pdf

And yes, we are closer!
![image](https://user-images.githubusercontent.com/7136948/148254716-c8981956-acb5-4c4e-9864-5628241783b6.png)

**Comment by uploader18** [comment] 2022-01-05 18:40
capture RX TX CLOCK

[puls-clock_tx_rx.zip](https://github.com/issalig/toshiba_air_cond/files/7817052/puls-clock_tx_rx.zip)

**Comment by issalig** [comment] 2022-01-06 08:36
Yes, it seems a mix of SPI  (TX) and serial (RX)
but serial bytes have no sense to me. SPI bytes look better.

If seria-ish protocol I would expect one of the bytes to be datalength and present values in the range 0-10  and they are much bigger.

![image](https://user-images.githubusercontent.com/7136948/148353407-896d3f1d-35cd-4e1f-ad9a-e54e3c5f6f1c.png)

**Comment by issalig** [comment] 2022-01-07 19:22
Do you have any progress?

**Comment by uploader18** [comment] 2022-01-07 22:02
No, for now i will try to invert RX line.I think it is some kind of custom com protocol.You...any luck?

**Comment by issalig** [comment] 2022-01-07 22:23
No, it is completely different from the remote controller, :(

**Comment by uploader18** [comment] 2022-01-08 11:54
maybe this helps, MCU on the board is NEC 780076GK and communication is connected to TX2 and RX2.

**Comment by issalig** [comment] 2022-01-11 11:05
I checked the doc and it seems to combine UART and SPI in some manner.

Also, I found this document https://www.cdlweb.info/wp-content/uploads/2018/07/Installation-Manual-TCB-IFLN642TLE.pdf
It seems that protocol in outdoor units is called TCC-LINK. I thought this was the one I decoded for indoor units, but I was wrong and it is called sth like AB protocol

**Comment by uploader18** [comment] 2022-01-11 21:25
TCC-LINK is for remote control of VRV,VRF systems that uses modbus communication, same as your display and is open to public and uses U1,U2 or A,B terminal to communicate, on the other hand internal machine to machine protocol is different from any known protocol.

**Comment by issalig** [comment] 2022-01-28 22:58
I was playing with the last data you sent but did not get any good result and you?

**Comment by issalig** [comment] 2022-04-07 07:42
Any news on this? Should I close the issue and open it later if needed?

**Closed** 2022-06-28 08:04 UTC

**Comment by uploader18** [comment] 2023-01-28 15:29
hey, good news, i figured it out but now i need help with checksum.

I get this data but no crc calculator works,

00 0F 00 34 00 21
10 5A 00 00 11 21
20 60 7F 53 00 1A
90 5A 00 00 11 20

Last byte is checksum i think?

Regards Žiga

**Comment by issalig** [comment] 2023-01-28 18:32
Nice, I am glad you solved it, will you document your work?

I have playing with a crc calculator but it does not give any reasonable values. Maybe your missing a byte? Also do not worry about crc, just read the important info and ignore crc.

**Comment by uploader18** [comment] 2023-01-28 19:51
ok so i managed crack that one too.

of you convert it to binary and count 0's in first 5 bytes you get checksum in last byte.

Regards Žiga

**Comment by uploader18** [comment] 2023-01-28 19:52
I cannot ignore checksum since i need it for two way communication.

**Comment by issalig** [comment] 2023-01-28 21:09
Great, how did you guess it?

**Comment by uploader18** [comment] 2023-01-28 21:33
just a lucky guess and trail and error like everything about this protocol, about documenting it is a little complicated since i don't think toshiba will be very happy about it and I can get a lawsuit for making it public. All of their outdoor units run on the same protocol, from first inverter AC to newest 2023 heat pump.What do you think?

**Comment by issalig** [comment] 2023-01-28 21:44
Well, as far you do not sell a product I do not see the problem.
But if you do not want to make it public, would it be ok for you to share the code with me? I am curious about what information is running from/to the outdoor unit.

**Comment by uploader18** [comment] 2023-01-28 21:58
indoor to outdoor
COMP. rev, TC sensor,TA sensor, heating/cooling, compressor on,error codes and indoor unit capacity

outdoor to indoor
actual COMP. rev, TE sensor,TO sensor,TD sensor,TS sensor, (heating/cooling, COMP on set confirmation), compressor current, defrost signal,error code, FAN rpm,PMV opening position, capacity code.

If you are willing to help me write arduino library for communication i will share all the data with you.

**Comment by issalig** [comment] 2023-01-29 10:44
I am just curious about the protocol. Last year I dedicated some hours to play with the data you provided and I would like to know how those signals were.

I can give you some hints about decoding it in arduino, moreover you have my code available to see how I solved it, this is the magic of open source :)

**Comment by 111lisu** [comment] 2023-11-17 16:09
@uploader18 Hello, would there be a chance for codes for (starting / heating the exchanger) for the external unit?
A fraudster sold me a RAV-SP804ATP-E and was supposed to send the indoor unit. I called the service center and they said the costs were high.

**Comment by milleroff** [comment] 2024-07-23 15:09
Hi guys, any progress on this ?
I have several Toshiba RAS-M16GDV-E ducted ACs and based on the service manual they have the same serial protocol as you discussed in this thread.

What i want to achieve is to control the AC from an arduino (set mode & temp) but i don't want to use IR for that.
Or maybe you know a modbus or other protocol gateway that could work with this kind of ACs ? (they don't have the AB or U[1-4] terminals).

Thanks !
